---
# tasks file for netscaler_lb_service_mgmt
    - name: Enable load balancing  services
      delegate_to: localhost
      citrix_adc_service:
         nsip: "{{ nsip }}"
         nitro_user: "{{ nitro_user }}"
         nitro_pass: "{{ nitro_pass }}"
         validate_certs: no
         disabled: false
         name: "{{ item }}"
      when: >-
          ( 'ENABLE' in service_status )
      with_items: "{{ service_name }}"

    - name: Disable load balancing services
      delegate_to: localhost
      citrix_adc_service:
         nsip: "{{ nsip }}"
         nitro_user: "{{ nitro_user }}"
         nitro_pass: "{{ nitro_pass }}"
         validate_certs: no
         disabled: true
         name: "{{ item }}"
      when: >-
          ( 'DISABLE' in service_status )
      with_items: "{{ service_name }}"
